---
title: "Rat Mapping"
runtime: shiny
output: flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(dplyr)
library(flexdashboard)
library(leaflet)
library(shiny)

library(leaflet.providers)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 7,
  out.width = "90%"
)


```




```{r import and clean obs, message = FALSE, warning=FALSE}

rat_sightings = 
  read_csv ("./data/Rat_Sightings.csv") |>
  janitor::clean_names(case = "snake") |>
  separate(created_date, sep="/", into = c("month", "day", "year")) |> 
  separate(year, sep=" ", into = c("year")) |>
  filter(borough != "STATEN ISLAND") |> 
  filter(year %in% c("2019", "2020", "2021", "2022", "2023")) |>
  mutate(
    borough_id = recode(
      borough, 
      "MANHATTAN" = 1,
      "BRONX" =2,
      "BROOKLYN"=3,
      "QUEENS"= 4)) |>
  mutate(
    month = as.numeric(month),
    year = as.numeric(year)
  ) |>
  select(unique_key, month, day, year, location_type, incident_zip, borough, location, borough_id) |>
  mutate(
    borough = str_to_sentence(borough)
  )
```


```{r mapping dataset}
map_rat_sightings<-rat_sightings %>% 
  filter(year=="2022") %>% 
  separate(location, into = c("latitude", "longitude"), sep = ",", remove = FALSE) %>%  
mutate(
    longitude = str_replace(longitude, "\\)", ""),
    latitude = str_replace(latitude, "\\(", ""),
    longitude = as.numeric(longitude),
    latitude = as.numeric(latitude)) 
```



```{r}
ui <- bootstrapPage(
  titlePanel("NYC Rat Sightings by Month, 2022"),
  tags$style(type = "text/css", "html, body {width:100%;height:100%}"),
  leafletOutput("map", width = "100%", height = "600px"),
  absolutePanel(top = 10, right = 10,
                sliderInput("animation", "Month", min(map_rat_sightings$month), max(map_rat_sightings$month),
                            value = min(map_rat_sightings$month), step = 1,
                            animate = animationOptions(interval = 600, loop = FALSE)
                )
  )
)

server <- function(input, output, session) {
  
  filteredData <- reactive({
    subset <- map_rat_sightings[map_rat_sightings$month == input$animation, ]
    subset <- subset[complete.cases(subset$latitude, subset$longitude), ]
    subset
  })
  
  output$map <- renderLeaflet({
    pal <- colorFactor(palette = "Dark2", domain = filteredData()$borough) 
    
    leaflet(data = filteredData()) %>%
      addTiles() %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      fitBounds(
        min(filteredData()$longitude),
        min(filteredData()$latitude),
        max(filteredData()$longitude),
        max(filteredData()$latitude)
      ) %>%
      addCircleMarkers(
        lat = ~latitude,  
        lng = ~longitude, 
        radius = 3,              
        stroke = FALSE,
        fillOpacity = 0.8,
        color = ~pal(borough)    
      )
  })
}

shinyApp(ui, server)
```

