---
title: "EDA"
---

### Exploratory Data Analysis

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(janitor)
library(dplyr)
library(ggplot2)
library(stats)
library(stats)
```


```{r packages, message = FALSE}
library(tidyverse)
library(tidyr)
library(readxl)
library(stringr)
library(dbplyr)
setwd("/Users/lvrt/Documents/Data Science I/Final Project - Laura")
```

## Cleaning rat sightings dataset

```{r import and clean obs, message = FALSE, warning=FALSE}
setwd("/Users/lvrt/Documents/Data Science I/Final Project - Laura")

rat_sightings = 
  read_csv ("./data/Rat_Sightings.csv") |>
  janitor::clean_names(case = "snake") |>
  separate(created_date, sep="/", into = c("month", "day", "year")) |> 
  separate(year, sep=" ", into = c("year")) |>
  filter(borough != "STATEN ISLAND") |> 
  filter(year %in% c("2019", "2020", "2021", "2022", "2023")) |>
  mutate(
    borough_id = recode(
      borough, 
      "MANHATTAN" = 1,
      "BRONX" =2,
      "BROOKLYN"=3,
      "QUEENS"= 4)) |>
  mutate(
    month = as.numeric(month),
    year = as.numeric(year)
  ) |>
  select(unique_key, month, day, year, location_type, incident_zip, borough, location, borough_id) |>
  mutate(
    borough = str_to_sentence(borough)
  )
```


### Data Cleaning for Waste Tonnage data (N)
```{r}
waste_tonnage = read_csv("./DSNY_Monthly_Tonnage_Data_20231202.csv") %>%
  clean_names(case = "snake") %>%
  mutate(date_split = strsplit(month, "/")) %>%
  mutate(
    year = as.integer(sapply(date_split, function(x) x[1])),
    month = as.integer(sapply(date_split, function(x) x[2]))
  ) %>%
  filter(year %in% c(2022, 2023)) %>% 
  mutate(total_organics = resorganicstons + schoolorganictons)

waste_tonnage = waste_tonnage %>% 
  group_by(borough, month, year, borough_id) %>% 
  summarise(
    total_organics = sum(total_organics, na.rm = TRUE),
    total_refuse = sum(refusetonscollected, na.rm = TRUE)
    )
```


### Merging rat sightings and waste tonnage data (N)
```{r}
rat_waste_merged = left_join(rat_sightings, waste_tonnage, by = c("borough_id", "month", "year", "borough"))
```

## filtering out the N/A's in a dataset (B)
```{r}
rat_waste_filtered = subset(rat_waste_merged, !is.na(total_organics) & !is.na(total_refuse))
```

## plot 1: total trash by borough for 2022 and 2023 (B)
```{r}
waste_tonnage_by_borough = rat_waste_filtered |> 
  group_by(borough) |> 
  summarise(total_tonnage = sum(total_organics + total_refuse))

ggplot(waste_tonnage_by_borough, aes(x = reorder(borough, -total_tonnage), y = total_tonnage)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(x = "Borough", y = "Trash Tonnage", title = "Trash Tonnage by Borough, 2022 - 2023") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## bar graph by total refuse and total organics (had to separate b/c they are on a different scale) (B)
```{r}
waste_by_borough_refuse <- aggregate(total_refuse ~ borough, data=waste_tonnage, sum)

# barplot for total refuse
barplot(waste_by_borough_refuse$total_refuse,
        main="Total Refuse Production by Borough",
        xlab="Borough",
        ylab="Total Refuse (tons)",
        col="blue",
        names.arg=waste_by_borough_refuse$borough,
        las=2)

waste_by_borough_organics <- aggregate(total_organics ~ borough, data=waste_tonnage, sum)

# barplot for total organics
barplot(waste_by_borough_organics$total_organics,
        main="Total Organics Production by Borough",
        xlab="Borough",
        ylab="Total Organics (tons)",
        col="green",
        names.arg=waste_by_borough_organics$borough,
        las=2)

```


## plot 2: trash by borough & month (B)
```{r}
total_tonnage_by_borough_year_month = rat_waste_filtered |> 
  group_by(borough, year, month) |> 
  summarise(total_tonnage = sum(total_organics + total_refuse))

total_tonnage_by_borough_year_month$year_month <- as.Date(paste(total_tonnage_by_borough_year_month$year, total_tonnage_by_borough_year_month$month, "01", sep = "-"))

ggplot(total_tonnage_by_borough_year_month, aes(x = year_month, y = total_tonnage, group = borough, color = borough)) +
  geom_line() +
  labs(x = "Year-Month", y = "Amount of Trash (in tons)", title = "Trash Tonnage by Month and Borough") +
  scale_x_date(date_labels = "%Y-%m", date_breaks = "1 month") +
  scale_y_continuous(labels = scales::number_format(scale = 1e-6)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
