<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>sda.knit</title>

<script src="site_libs/header-attrs-2.24/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Introduction</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="eda.html">Exploratory Data Analysis</a>
</li>
<li>
  <a href="sda.html">Statistical Data Analysis</a>
</li>
<li>
  <a href="final_report.html">Final Report</a>
</li>
<li>
  <a href="about.html">About us</a>
</li>
<li>
  <a href="rat_mapping2.html">Maps</a>
</li>
<li>
  <a href="mailto:&lt;lvr2115@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/yyNYFL/Final-Project">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>




</div>


<div id="statistical-data-analysis" class="section level2 tabset">
<h2 class="tabset">Statistical Data Analysis</h2>
<div id="rat-sightings-analysis" class="section level3">
<h3>Rat Sightings Analysis</h3>
<div id="anova." class="section level4">
<h4>ANOVA.</h4>
<p>Analysis of variance of the average rat sightings we saw in the
‘rat_boro’ kable output. We can see that there are differences in the
average rat sightings across years and boros so we wanted to explore if
thiese diferences were statistically significant through a ANOVA
test.</p>
<pre class="r"><code>rat_sightings = 
  read_csv (&quot;./data/Rat_Sightings.csv&quot;) |&gt;
  janitor::clean_names(case = &quot;snake&quot;) |&gt;
  separate(created_date, sep=&quot;/&quot;, into = c(&quot;month&quot;, &quot;day&quot;, &quot;year&quot;)) |&gt; 
  separate(year, sep=&quot; &quot;, into = c(&quot;year&quot;)) |&gt;
  filter(borough != &quot;STATEN ISLAND&quot;) |&gt; 
  filter(year %in% c(&quot;2019&quot;, &quot;2020&quot;, &quot;2021&quot;, &quot;2022&quot;, &quot;2023&quot;)) |&gt;
  mutate(
    borough_id = recode(
      borough, 
      &quot;MANHATTAN&quot; = 1,
      &quot;BRONX&quot; =2,
      &quot;BROOKLYN&quot;=3,
      &quot;QUEENS&quot;= 4)) |&gt;
  mutate(
    month = as.numeric(month),
    year = as.numeric(year)
  ) |&gt;
  select(unique_key, month, day, year, location_type, incident_zip, borough, location, borough_id) |&gt;
  mutate(
    borough = str_to_sentence(borough)
  )
rat_sightings_agg = rat_sightings |&gt; 
  group_by(year, borough, month) |&gt; 
  filter(borough != &quot;Unspecified&quot;) %&gt;% 
  summarise(count = n())

anova_result = aov(count ~ factor(year) * factor(borough), data = rat_sightings_agg) 
broom::tidy(anova_result)</code></pre>
<pre><code>## # A tibble: 4 × 6
##   term                            df    sumsq   meansq statistic   p.value
##   &lt;chr&gt;                        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 factor(year)                     4 2185688.  546422.     33.0   1.86e-21
## 2 factor(borough)                  3 6927195. 2309065.    139.    3.02e-50
## 3 factor(year):factor(borough)    12  548327.   45694.      2.76  1.66e- 3
## 4 Residuals                      216 3579973.   16574.     NA    NA</code></pre>
<pre class="r"><code>anova_result_no_interaction = aov(count ~ factor(year) + factor(borough), data = rat_sightings_agg) 
broom::tidy(anova_result_no_interaction)</code></pre>
<pre><code>## # A tibble: 3 × 6
##   term               df    sumsq   meansq statistic   p.value
##   &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 factor(year)        4 2185688.  546422.      30.2  3.72e-20
## 2 factor(borough)     3 6927195. 2309065.     128.   1.63e-48
## 3 Residuals         228 4128300.   18107.      NA   NA</code></pre>
<p>We want to check the assumptions for the ANOVA models ran above.
There are three assumptions that should be met when computing an
ANOVA:</p>
<p>-The response variable must be quantitative- This is met since the
response variable of count of rat sightings is quantitative. -The
variance between the groups of average rat sightings by borough and by
year should be similar and in this case they are. -Observations should
be independent of one another- which we are assuming is satisfied. -The
distribution of values within each group of rat sightings by borough is
normally distributed which we can see in some of the plots. We can also
check the normality of residuals in the below code. From the Normal Q-Q
plot of both model residuals the points are quite close to the fitted
diagonal line. We also conducted Shapiro-Wilk tests for normality of
residuals for both models and with a null hypothesis that the residuals
follow a normal distribution and an alternative hypothesis that the
residuals does not follow a normal distribution. The p-value for the no
interaction model is 0.2694 and the p-value for the interaction model is
0.03883. At a 5% level of significance we can conclude the residuals of
the interaction model follow a normal distribution but the residuals for
the no interaction model do not follow a normal distribution.
###Checking assumptions of ANOVA</p>
<pre class="r"><code># Extract residuals for the interaction model
residuals_interaction &lt;- residuals(anova_result)

# Check normality of residuals for the interaction model
qqnorm(anova_result$residuals)
qqline(anova_result$residuals)</code></pre>
<p><img src="sda_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code># Shapiro-Wilk test for normality
shapiro.test(anova_result$residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  anova_result$residuals
## W = 0.98759, p-value = 0.03883</code></pre>
<pre class="r"><code># Extract residuals for the interaction model
residuals_no_interaction &lt;- residuals(anova_result_no_interaction)

# Check normality of residuals for the model without interaction
qqnorm(residuals_no_interaction)
qqline(residuals_no_interaction)</code></pre>
<p><img src="sda_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<pre class="r"><code># Shapiro-Wilk test for normality
shapiro.test(anova_result_no_interaction$residuals)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  anova_result_no_interaction$residuals
## W = 0.99244, p-value = 0.2694</code></pre>
<pre class="r"><code># Shapiro-Wilk test for normality
shapiro.test(residuals_no_interaction)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals_no_interaction
## W = 0.99244, p-value = 0.2694</code></pre>
<pre class="r"><code># Check homoscedasticity for the interaction model
plot(anova_result$model)

# Check homoscedasticity for the model without interaction
plot(anova_result_no_interaction$model)</code></pre>
<p><img src="sda_files/figure-html/unnamed-chunk-1-3.png" width="672" /></p>
<p>From the ANOVA test for the model with the interaction which is the
model that checked all of the assumptions of an ANOVA test above we can
see from the p-value of being &lt;0.001 at 5% level of significance we
can reject the null hypotheses and conclude that at least one of the
average rat sightings by borough and by year are statistically
different.</p>
</div>
</div>
<div id="waste-tonnage-analysis" class="section level3">
<h3>Waste Tonnage Analysis</h3>
<p>The dataset was cleaned to ensure accurate and relevant data for
analysis. We performed the following steps:</p>
<ul>
<li>Standardized column names</li>
<li>Parsed and converted date information</li>
<li>Filtered data for the years 2022 and 2023</li>
<li>Calculated total organics by summing relevant columns</li>
<li>Aggregated waste tonnage by borough and date</li>
</ul>
<div id="anova-for-differences-in-waste-tonnage-across-boroughs"
class="section level4">
<h4>ANOVA for Differences in Waste Tonnage Across Boroughs</h4>
<p>We conducted one-way ANOVA tests to compare the total organic and
refuse waste tonnage across boroughs. Before interpreting the ANOVA
results, we checked the assumptions of normality and homogeneity of
variances.</p>
<ul>
<li>Homogeneity of variances, the assumption that the variance within
each group is the same, was checked using Bartlett’s test. A
non-significant result (p &gt; 0.05) would suggest that this assumption
holds true.</li>
<li>For normality, we examined the residuals of our ANOVA model. The
residuals should follow a normal distribution for the ANOVA results to
be valid. This was checked using Q-Q plots, where a close alignment of
the residuals with the reference line would indicate normality.</li>
</ul>
</div>
<div id="anova-test-for-organic-waste-tonnage" class="section level4">
<h4>ANOVA Test for Organic Waste Tonnage</h4>
<pre class="r"><code>anova_model_organics &lt;- aov(total_organics ~ borough, data = waste_tonnage)
anova_result_organics &lt;- broom::tidy(anova_model_organics)</code></pre>
</div>
<div id="anova-test-for-refuse-waste-tonnage" class="section level4">
<h4>ANOVA Test for Refuse Waste Tonnage</h4>
<pre class="r"><code>anova_model_refuse &lt;- aov(total_refuse ~ borough, data = waste_tonnage)
anova_result_refuse &lt;- broom::tidy(anova_model_refuse)</code></pre>
</div>
<div id="assumption-checks" class="section level4">
<h4>Assumption Checks</h4>
<pre class="r"><code># Normality check with Q-Q plots
qqnorm(anova_model_organics$residuals)
qqline(anova_model_organics$residuals)</code></pre>
<p><img src="sda_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>qqnorm(anova_model_refuse$residuals)
qqline(anova_model_refuse$residuals)</code></pre>
<p><img src="sda_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code># Homogeneity of variances check with Bartlett&#39;s test
bartlett_test_organics &lt;- bartlett.test(total_organics ~ borough, data = waste_tonnage)
bartlett_test_refuse &lt;- bartlett.test(total_refuse ~ borough, data = waste_tonnage)</code></pre>
<pre class="r"><code># Output ANOVA results
list(anova_result_organics, anova_result_refuse)</code></pre>
<pre><code>## [[1]]
## # A tibble: 2 × 6
##   term         df    sumsq  meansq statistic      p.value
##   &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
## 1 borough       4 2701708. 675427.      10.5  0.000000296
## 2 Residuals   112 7209968.  64375.      NA   NA          
## 
## [[2]]
## # A tibble: 2 × 6
##   term         df        sumsq      meansq statistic   p.value
##   &lt;chr&gt;     &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 borough       4 37843283363. 9460820841.      82.1  2.19e-32
## 2 Residuals   112 12913077883.  115295338.      NA   NA</code></pre>
<p>The one-way ANOVA test was performed to assess the differences in
organic waste tonnage among the boroughs. The ANOVA test revealed
statistically significant differences in organic waste tonnage among the
boroughs (F(4, 112) = 10.5, p &lt; 0.05).</p>
<p>A one-way ANOVA test was conducted to examine the differences in
refuse waste tonnage among the boroughs.The ANOVA test revealed
statistically significant differences in refuse waste tonnage among the
boroughs (F(4, 112) = 82.1, p &lt; 0.001).</p>
</div>
</div>
<div id="linear-model" class="section level3">
<h3>Linear Model</h3>
<p>The rat sightings data set was cleaned to show the number of rat
sightings for 2022 and 2023 by year, month, and borough. Then, the rat
sightings data was merged with the waste tonnage data by year, month,
and borough.</p>
<pre class="r"><code>rat_count_month &lt;- rat_sightings %&gt;% 
  select(unique_key, month, year, borough, borough_id) %&gt;% 
  filter(year %in% c(&quot;2022&quot;, &quot;2023&quot;), borough != &quot;Unspecified&quot;) %&gt;%
  group_by(borough, borough_id, year, month) %&gt;% 
  summarise(sighting_n = n_distinct(unique_key)) 


rat_waste_month_merged = left_join(rat_count_month, waste_tonnage, by = c(&quot;borough_id&quot;, &quot;month&quot;, &quot;year&quot;, &quot;borough&quot;))%&gt;% 
  mutate(month=as.character(month),
         year=as.character(year))</code></pre>
<div
id="linear-regression-model-for-the-number-of-rat-sightings-by-total-refuse-borough-year-and-month."
class="section level4">
<h4>Linear Regression model for the number of rat sightings by total
refuse, borough, year, and month.</h4>
<pre class="r"><code>rat_sightings_fit &lt;- lm(sighting_n ~ total_refuse + borough + year, data = rat_waste_month_merged)</code></pre>
<p>y(Number of Rat Sightings) = Intercept + Total Waste (x<sub>1</sub>)
+ Borough (x<sub>2</sub>) + Year (x<sub>3</sub>)</p>
<pre class="r"><code>rat_sightings_fit |&gt; 
  broom::glance()|&gt; 
  knitr::kable(digits = 3)</code></pre>
<table style="width:100%;">
<colgroup>
<col width="9%" />
<col width="13%" />
<col width="7%" />
<col width="9%" />
<col width="7%" />
<col width="2%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="11%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.752</td>
<td align="right">0.737</td>
<td align="right">129.797</td>
<td align="right">52.096</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">-575.109</td>
<td align="right">1164.219</td>
<td align="right">1181.871</td>
<td align="right">1448862</td>
<td align="right">86</td>
<td align="right">92</td>
</tr>
</tbody>
</table>
<p>With an R<sup>2</sup> = 0.752, the independent variables (total
waste, borough, year) in this model appear to explain about 75.2.2% of
the variance in the dependent variable (number of rat sightings).</p>
<pre class="r"><code>rat_sightings_fit|&gt; 
  broom::tidy() |&gt; 
  select(term, estimate, std.error, statistic, p.value) |&gt; 
  mutate(term = str_replace(term, &quot;^borough&quot;, &quot;Borough: &quot;)) |&gt; 
  mutate(term = str_replace(term, &quot;^total_refuse&quot;, &quot;Total Waste&quot;)) |&gt; 
  mutate(term = str_replace(term, &quot;^year&quot;, &quot;Year: &quot;)) |&gt; 
  knitr::kable(digits = 6)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">137.557270</td>
<td align="right">63.639726</td>
<td align="right">2.161500</td>
<td align="right">0.033436</td>
</tr>
<tr class="even">
<td align="left">Total Waste</td>
<td align="right">0.005532</td>
<td align="right">0.001618</td>
<td align="right">3.418234</td>
<td align="right">0.000965</td>
</tr>
<tr class="odd">
<td align="left">Borough: Brooklyn</td>
<td align="right">343.724245</td>
<td align="right">66.843236</td>
<td align="right">5.142244</td>
<td align="right">0.000002</td>
</tr>
<tr class="even">
<td align="left">Borough: Manhattan</td>
<td align="right">275.870898</td>
<td align="right">38.331153</td>
<td align="right">7.197042</td>
<td align="right">0.000000</td>
</tr>
<tr class="odd">
<td align="left">Borough: Queens</td>
<td align="right">-101.084602</td>
<td align="right">54.651270</td>
<td align="right">-1.849629</td>
<td align="right">0.067802</td>
</tr>
<tr class="even">
<td align="left">Year: 2023</td>
<td align="right">15.873828</td>
<td align="right">27.867071</td>
<td align="right">0.569627</td>
<td align="right">0.570416</td>
</tr>
</tbody>
</table>
</div>
<div id="interpretations" class="section level4">
<h4>Interpretations:</h4>
<p>Total Waste - For every unit increase in total waste, the number of
rat sightings increased by 0.005532, adjusting for borough, and year. At
a 5% level of significance, there was a statistically significant
relationship between the number of rat sightings and the total waste
(<em>P</em>&lt;0.001).</p>
<p>Year -There was not a statistically significant relationship between
the number of rat sightings and year at the 5% level of significance
(<em>P</em>=0.57), adjusting for total waste and year.</p>
<p>Borough:</p>
<p>Queens: The number of rat sightings in Queens was not significantly
different from the numnber of rat sightings in the Bronx at the 5% level
of significance (<em>P</em>=0.007), adjusting for total waste and
year.</p>
<p>Manhattan: The number of rat sightings in Manhattan was significantly
different from the number of rat sightings in the Bronx at the 5% level
of significance (<em>P</em>&lt;0.001), adjusting for total waste and
year.</p>
<p>Brooklyn: The number of rat sightings in Manhattan was significantly
different from the number of rat sightings in the Bronx at the 5% level
of significance (<em>P</em>&lt;0.001), adjusting for total waste and
year.</p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
